/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getUserFromEnv(): string
export declare function grabVirajmSite(): string
export declare function grabVirajmSiteAsync(): Promise<string>
export interface TimeAndNfl {
  time: string
  team: string
}
export declare function getTimeAndNfl(): TimeAndNfl
export interface Coefficients {
  a: number
  b: number
  c: number
}
export const enum SolutionType {
  OneRealRoot = 0,
  TwoRealRoots = 1
}
export interface Solution {
  solutionType: SolutionType
  root1: number
  root2?: number
}
export declare function solveQuadratic(coefficients: Coefficients): Solution
export declare function sleepy(): Promise<string>
export type ClientExample = Client
export declare class Client {
  envValue: string
  constructor(envName: string)
  getValue(): string
  getTensorzeroWebsite(): Promise<string>
}
